[package]
name = "p10k-rs-jj"
description = "Jujutsu (jj) VCS detection + state producer for p10k-rs."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p10k-rs-core = { workspace = true }

[lints]
workspace = true
