[package]
name = "p10k-rs-segments"
description = "Segment implementations for p10k-rs (dir, vcs, status, prompt_char, etc)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p10k-rs-core = { workspace = true }
p10k-rs-config = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
anstyle = { workspace = true }

[lints]
workspace = true
