[package]
name = "p10k-rs"
description = "A Rust port and spiritual successor to Powerlevel10k. Single static prompt binary."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "p10k-rs"
path = "src/main.rs"

[dependencies]
# Internal crates wire in as their respective subcommands light up.
p10k-rs-core = { workspace = true }
p10k-rs-git = { workspace = true }
p10k-rs-segments = { workspace = true }
p10k-rs-shell = { workspace = true }

clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
